### ISSUE TITLE
Fix Net::OpenTimeout in seeds

### ISSUE THREAD

**Issue by veganstraightedge** [ethiodotapp/ethio-api#2]
When running `rake db:seed`, I always get a `Net::OpenTimeout` error.

When I run it with 10 threads, it seems to happen around 3000 successfully saved blocks.

When I use more threads, it happens sooner.

The problem I'm trying to solve by using threads is how long it'll take to import the whole blockchain. 

At the time of writing this issue, there are about 5.5 million blocks. To import them all 1 by 1 would take a couple months. Doing it with 10 threads would be 10x faster, obviously. 100 threads, 100x faster. So on. 

I would like to use a lot of threads here to do this, but not fail from `Net::OpenTimeout`, stopping the whole process.

```
#<Thread:0x00007fa9ff8c9780@/…/ethio/ethio-api/db/seeds.rb:51 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
  10: from /Users/s/Documents/Projects/ethio/ethio-api/db/seeds.rb:53:in `block (3 levels) in <main>'
   9: from /Users/s/.gem/ruby/2.5.1/gems/web3-eth-0.2.15/lib/web3/eth/eth_module.rb:20:in `getBlockByNumber'
   8: from /Users/s/.gem/ruby/2.5.1/gems/web3-eth-0.2.15/lib/web3/eth/rpc.rb:38:in `request'
   7: from /Users/s/.rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:609:in `start'
   6: from /Users/s/.rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:909:in `start'
   5: from /Users/s/.rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
   4: from /Users/s/.rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:935:in `connect'
   3: from /Users/s/.rubies/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
   2: from /Users/s/.rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
   1: from /Users/s/.rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `open'
/Users/s/.rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `initialize': execution expired (Net::OpenTimeout)
rails aborted!
Net::OpenTimeout: execution expired
/Users/s/.gem/ruby/2.5.1/gems/web3-eth-0.2.15/lib/web3/eth/rpc.rb:38:in `request'
/Users/s/.gem/ruby/2.5.1/gems/web3-eth-0.2.15/lib/web3/eth/eth_module.rb:20:in `getBlockByNumber'
…/ethio/ethio-api/db/seeds.rb:53:in `block (3 levels) in <main>'
```

**Comment by veganstraightedge** [comment]
Fixed by moving back to using Concurrent Ruby in batches of 1000.
